#############################################################################
# Makefile for building: Flurry
# Generated by qmake (3.0) (Qt 5.3.1)
# Project:  Flurry.pro
# Template: app
# Command: /opt/Qt/5.3/gcc_64/bin/qmake -spec linux-g++ CONFIG+=debug -o Makefile Flurry.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = 
CFLAGS        = -pipe -g -Wall -W -fPIE $(DEFINES)
CXXFLAGS      = -pipe -std=c++11 -g -Wall -W -fPIE $(DEFINES)
INCPATH       = -I/opt/Qt/5.3/gcc_64/mkspecs/linux-g++ -I.
LINK          = g++
LFLAGS        = -Wl,-rpath,/opt/Qt/5.3/gcc_64
LIBS          = $(SUBLIBS)  
AR            = ar cqs
RANLIB        = 
QMAKE         = /opt/Qt/5.3/gcc_64/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/global.cpp \
		src/matrix.cpp \
		src/input.cpp \
		src/ele.cpp \
		src/polynomials.cpp \
		src/operators.cpp \
		src/geo.cpp \
		src/output.cpp \
		src/face.cpp \
		src/flux.cpp \
		src/flurry.cpp \
		src/solver.cpp 
OBJECTS       = global.o \
		matrix.o \
		input.o \
		ele.o \
		polynomials.o \
		operators.o \
		geo.o \
		output.o \
		face.o \
		flux.o \
		flurry.o \
		solver.o
DIST          = README.md \
		planning \
		/opt/Qt/5.3/gcc_64/mkspecs/features/spec_pre.prf \
		/opt/Qt/5.3/gcc_64/mkspecs/common/shell-unix.conf \
		/opt/Qt/5.3/gcc_64/mkspecs/common/unix.conf \
		/opt/Qt/5.3/gcc_64/mkspecs/common/linux.conf \
		/opt/Qt/5.3/gcc_64/mkspecs/common/gcc-base.conf \
		/opt/Qt/5.3/gcc_64/mkspecs/common/gcc-base-unix.conf \
		/opt/Qt/5.3/gcc_64/mkspecs/common/g++-base.conf \
		/opt/Qt/5.3/gcc_64/mkspecs/common/g++-unix.conf \
		/opt/Qt/5.3/gcc_64/mkspecs/qconfig.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_core.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_enginio.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_help.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_network.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_script.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/features/qt_functions.prf \
		/opt/Qt/5.3/gcc_64/mkspecs/features/qt_config.prf \
		/opt/Qt/5.3/gcc_64/mkspecs/linux-g++/qmake.conf \
		/opt/Qt/5.3/gcc_64/mkspecs/features/spec_post.prf \
		/opt/Qt/5.3/gcc_64/mkspecs/features/exclusive_builds.prf \
		/opt/Qt/5.3/gcc_64/mkspecs/features/default_pre.prf \
		/opt/Qt/5.3/gcc_64/mkspecs/features/resolve_config.prf \
		/opt/Qt/5.3/gcc_64/mkspecs/features/default_post.prf \
		/opt/Qt/5.3/gcc_64/mkspecs/features/warn_on.prf \
		/opt/Qt/5.3/gcc_64/mkspecs/features/testcase_targets.prf \
		/opt/Qt/5.3/gcc_64/mkspecs/features/exceptions.prf \
		/opt/Qt/5.3/gcc_64/mkspecs/features/yacc.prf \
		/opt/Qt/5.3/gcc_64/mkspecs/features/lex.prf \
		Flurry.pro src/global.cpp \
		src/matrix.cpp \
		src/input.cpp \
		src/ele.cpp \
		src/polynomials.cpp \
		src/operators.cpp \
		src/geo.cpp \
		src/output.cpp \
		src/face.cpp \
		src/flux.cpp \
		src/flurry.cpp \
		src/solver.cpp
QMAKE_TARGET  = Flurry
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = Flurry


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Flurry.pro /opt/Qt/5.3/gcc_64/mkspecs/linux-g++/qmake.conf /opt/Qt/5.3/gcc_64/mkspecs/features/spec_pre.prf \
		/opt/Qt/5.3/gcc_64/mkspecs/common/shell-unix.conf \
		/opt/Qt/5.3/gcc_64/mkspecs/common/unix.conf \
		/opt/Qt/5.3/gcc_64/mkspecs/common/linux.conf \
		/opt/Qt/5.3/gcc_64/mkspecs/common/gcc-base.conf \
		/opt/Qt/5.3/gcc_64/mkspecs/common/gcc-base-unix.conf \
		/opt/Qt/5.3/gcc_64/mkspecs/common/g++-base.conf \
		/opt/Qt/5.3/gcc_64/mkspecs/common/g++-unix.conf \
		/opt/Qt/5.3/gcc_64/mkspecs/qconfig.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_core.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_enginio.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_help.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_network.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_script.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/features/qt_functions.prf \
		/opt/Qt/5.3/gcc_64/mkspecs/features/qt_config.prf \
		/opt/Qt/5.3/gcc_64/mkspecs/linux-g++/qmake.conf \
		/opt/Qt/5.3/gcc_64/mkspecs/features/spec_post.prf \
		/opt/Qt/5.3/gcc_64/mkspecs/features/exclusive_builds.prf \
		/opt/Qt/5.3/gcc_64/mkspecs/features/default_pre.prf \
		/opt/Qt/5.3/gcc_64/mkspecs/features/resolve_config.prf \
		/opt/Qt/5.3/gcc_64/mkspecs/features/default_post.prf \
		/opt/Qt/5.3/gcc_64/mkspecs/features/warn_on.prf \
		/opt/Qt/5.3/gcc_64/mkspecs/features/testcase_targets.prf \
		/opt/Qt/5.3/gcc_64/mkspecs/features/exceptions.prf \
		/opt/Qt/5.3/gcc_64/mkspecs/features/yacc.prf \
		/opt/Qt/5.3/gcc_64/mkspecs/features/lex.prf \
		Flurry.pro
	$(QMAKE) -spec linux-g++ CONFIG+=debug -o Makefile Flurry.pro
/opt/Qt/5.3/gcc_64/mkspecs/features/spec_pre.prf:
/opt/Qt/5.3/gcc_64/mkspecs/common/shell-unix.conf:
/opt/Qt/5.3/gcc_64/mkspecs/common/unix.conf:
/opt/Qt/5.3/gcc_64/mkspecs/common/linux.conf:
/opt/Qt/5.3/gcc_64/mkspecs/common/gcc-base.conf:
/opt/Qt/5.3/gcc_64/mkspecs/common/gcc-base-unix.conf:
/opt/Qt/5.3/gcc_64/mkspecs/common/g++-base.conf:
/opt/Qt/5.3/gcc_64/mkspecs/common/g++-unix.conf:
/opt/Qt/5.3/gcc_64/mkspecs/qconfig.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_core.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_declarative.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_designer.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_enginio.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_gui.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_help.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_network.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_qml.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_quick.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_script.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_script_private.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_sql.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_svg.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_webkit.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_websockets.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_xml.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/opt/Qt/5.3/gcc_64/mkspecs/features/qt_functions.prf:
/opt/Qt/5.3/gcc_64/mkspecs/features/qt_config.prf:
/opt/Qt/5.3/gcc_64/mkspecs/linux-g++/qmake.conf:
/opt/Qt/5.3/gcc_64/mkspecs/features/spec_post.prf:
/opt/Qt/5.3/gcc_64/mkspecs/features/exclusive_builds.prf:
/opt/Qt/5.3/gcc_64/mkspecs/features/default_pre.prf:
/opt/Qt/5.3/gcc_64/mkspecs/features/resolve_config.prf:
/opt/Qt/5.3/gcc_64/mkspecs/features/default_post.prf:
/opt/Qt/5.3/gcc_64/mkspecs/features/warn_on.prf:
/opt/Qt/5.3/gcc_64/mkspecs/features/testcase_targets.prf:
/opt/Qt/5.3/gcc_64/mkspecs/features/exceptions.prf:
/opt/Qt/5.3/gcc_64/mkspecs/features/yacc.prf:
/opt/Qt/5.3/gcc_64/mkspecs/features/lex.prf:
Flurry.pro:
qmake: FORCE
	@$(QMAKE) -spec linux-g++ CONFIG+=debug -o Makefile Flurry.pro

qmake_all: FORCE

dist: 
	@test -d .tmp/Flurry1.0.0 || mkdir -p .tmp/Flurry1.0.0
	$(COPY_FILE) --parents $(DIST) .tmp/Flurry1.0.0/ && (cd `dirname .tmp/Flurry1.0.0` && $(TAR) Flurry1.0.0.tar Flurry1.0.0 && $(COMPRESS) Flurry1.0.0.tar) && $(MOVE) `dirname .tmp/Flurry1.0.0`/Flurry1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/Flurry1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

check: first

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

global.o: src/global.cpp include/global.hpp \
		include/matrix.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o global.o src/global.cpp

matrix.o: src/matrix.cpp include/matrix.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o matrix.o src/matrix.cpp

input.o: src/input.cpp include/input.hpp \
		include/global.hpp \
		include/matrix.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o input.o src/input.cpp

ele.o: src/ele.cpp include/ele.hpp \
		include/global.hpp \
		include/matrix.hpp \
		include/geo.hpp \
		include/input.hpp \
		include/solver.hpp \
		include/face.hpp \
		include/operators.hpp \
		include/polynomials.hpp \
		include/flux.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ele.o src/ele.cpp

polynomials.o: src/polynomials.cpp include/polynomials.hpp \
		include/global.hpp \
		include/matrix.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o polynomials.o src/polynomials.cpp

operators.o: src/operators.cpp include/operators.hpp \
		include/global.hpp \
		include/matrix.hpp \
		include/geo.hpp \
		include/input.hpp \
		include/solver.hpp \
		include/ele.hpp \
		include/face.hpp \
		include/polynomials.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o operators.o src/operators.cpp

geo.o: src/geo.cpp include/geo.hpp \
		include/global.hpp \
		include/matrix.hpp \
		include/input.hpp \
		include/solver.hpp \
		include/ele.hpp \
		include/face.hpp \
		include/operators.hpp \
		include/polynomials.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o geo.o src/geo.cpp

output.o: src/output.cpp include/output.hpp \
		include/global.hpp \
		include/matrix.hpp \
		include/solver.hpp \
		include/ele.hpp \
		include/geo.hpp \
		include/input.hpp \
		include/face.hpp \
		include/operators.hpp \
		include/polynomials.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o output.o src/output.cpp

face.o: src/face.cpp include/face.hpp \
		include/global.hpp \
		include/matrix.hpp \
		include/ele.hpp \
		include/geo.hpp \
		include/input.hpp \
		include/solver.hpp \
		include/operators.hpp \
		include/polynomials.hpp \
		include/flux.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o face.o src/face.cpp

flux.o: src/flux.cpp include/flux.hpp \
		include/global.hpp \
		include/matrix.hpp \
		include/input.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o flux.o src/flux.cpp

flurry.o: src/flurry.cpp include/flurry.hpp \
		include/global.hpp \
		include/matrix.hpp \
		include/input.hpp \
		include/geo.hpp \
		include/solver.hpp \
		include/ele.hpp \
		include/face.hpp \
		include/operators.hpp \
		include/polynomials.hpp \
		include/output.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o flurry.o src/flurry.cpp

solver.o: src/solver.cpp include/solver.hpp \
		include/global.hpp \
		include/matrix.hpp \
		include/ele.hpp \
		include/geo.hpp \
		include/input.hpp \
		include/face.hpp \
		include/operators.hpp \
		include/polynomials.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o solver.o src/solver.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

